### ISSUE TITLE
Analytics Tracking Code causes failure due to Browser Detection 

### ISSUE THREAD

**Issue by m-gagne** [MicrosoftEdge/static-code-scan#100]
Various analytics/tracking scripts will often pass browser information back to the collection service. One example is the Adobe Visitor Tracking API (Omniture) which uses `navigator.userAgent` to record browser information.

Should there be a whitelist of scripts that are ignored if their use of browser detection code does not affect the markup or features of the site?

Example offending code:

```
var t = e({
    OmniWeb: /OmniWeb/,
    "Opera Mini": /Opera Mini/,
    "Opera Mobile": /Opera Mobi/,
    Opera: /Opera/,
    "Mobile Safari": /Mobile(\/[0-9A-z]+)? Safari/,
    Chrome: /Chrome/,
    Firefox: /Firefox/,
    "IE Mobile": /IEMobile/,
    IE: /MSIE|Trident/,
    Safari: /Safari/
}),
    n = e({
        iOS: /iPhone|iPad|iPod/,
        Blackberry: /BlackBerry/,
        "Symbian OS": /SymbOS/,
        Maemo: /Maemo/,
        Android: /Android [0-9\.]+;/,
        Linux: / Linux /,
        Unix: /FreeBSD|OpenBSD|CrOS/,
        Windows: /[\( ]Windows /,
        MacOS: /Macintosh;/
    }),
    a = e({
        iPhone: /iPhone/,
        iPad: /iPad/,
        iPod: /iPod/,
        Nokia: /SymbOS|Maemo/,
        "Windows Phone": /IEMobile/,
        Blackberry: /BlackBerry/,
        Android: /Android [0-9\.]+;/,
        Desktop: /.*/
    }),
    i = navigator.userAgent;
k.browserInfo = {
    browser: t(i),
    os: n(i),
    deviceType: a(i)
}
```

**Comment by molant** [comment]
We are ignoring files with known names and domains in here: https://github.com/MicrosoftEdge/static-code-scan/blob/master/lib/checks/check-browser-detection.js#L34

I think that we are also scanning for files in the same domain only, but not 100% sure.

Feel free to do a PR!

**Comment by m-gagne** [comment]
Ok, this will be more than a file whitelist as the filename is specific to the site, would it be ok to do a header check? The file in question contains "Adobe Visitor API for JavaScript version: 1.5" so I could build a regex that looks for "Adobe Visitor API for JavaScript version: \d\.\d"

**Comment by molant** [comment]
This project is deprecated and no longer maintained. Please check [sonar](https://github.com/sonarwhal/sonar) if you need a similar tool but more flexible and modern.
