### ISSUE TITLE
Unable to Set-up With CLI

### ISSUE THREAD

**Issue by reddysainathn** [MicrosoftEdge/static-code-scan#106]
I am unable to run CLI command,is there anything that I am suppose to do for setting up CLI , it works file with node app.js ,but not able to run with static-code-scan,can you help me with this ,and also does this application support https?

When I run the https in the browser,it says "Report generation is not currently working. Please use the CLI".
![git](https://cloud.githubusercontent.com/assets/10643404/12147590/5a91a4ec-b45f-11e5-83bf-6d7161e3b24a.PNG)
I am not able to find any information to set-up CLI,so I am reaching out here.

**Comment by molant** [comment]
The instructions to run the CLI are in https://github.com/MicrosoftEdge/static-code-scan/blob/master/README.md#cli
instead of running `node app.js` you run `static-code-scan`
The gif in the instructions hopefully make it clear.

**Comment by reddysainathn** [comment]
This is what happening with me,can you please guide me to run the test with CLI,if there is anything that I can follow to setup.
I have done npm install and node app.js is working fine ,but I need CLI to work.
![capture](https://cloud.githubusercontent.com/assets/10643404/12162956/3943717a-b4ce-11e5-8324-aa3b34086897.PNG)
Thank You.

**Comment by molant** [comment]
Try running `node bin\static-code-scan.js` from the root of the project.

**Comment by reddysainathn** [comment]
Thank you
