### ISSUE TITLE
Wrong version-Detection for js-library

### ISSUE THREAD

**Issue by cyper85** [MicrosoftEdge/static-code-scan#107]
I use jquery 1.12.0. It's the latest version on the 1.*-tree. But the scanner doesn't detect the version correct and mark it as an error.

![Screenshot](https://pbs.twimg.com/media/CYxpSJCW8AQJvEN.png:large)

**Comment by marknoble** [comment]
I'm using 2.2.0 and also getting an error.

Here's the static-code-scan result.

```
  jslibs                                                                        │    ×
────────────────────────────────────────────────────────────────────────────────┴──────────
  [
    {
      "name": "jQuery",
      "needsUpdate": true,
      "minVersion": "1.6.4",
      "version": "2.2.0",
      "url": "//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js",
      "lineNumber": 9
    }
  ]
```

I can't find the string "1.6.4" anywhere in my code so... wondering where that's coming from.

**Comment by dmethvin** [comment]
It should be fixed by #109, I meant to reference this ticket in the PR.

**Comment by dmethvin** [comment]
Since new releases have happened, I'll just reference this ticket with a new PR.

**Comment by molant** [comment]
This project is deprecated and no longer maintained. Please check [sonar](https://github.com/sonarwhal/sonar) if you need a similar tool but more flexible and modern.
