### ISSUE TITLE
سوال مهم 

### ISSUE THREAD

**Issue by farzanefarahan** [MicrosoftEdge/static-code-scan#116]
سلام 
چگونه میشود از مرورگر اینترنت اکسپلورر در گوشی تلفن همراه و موبایل با سیستم اندروید استفاده کرد و سایت هایی که فقط با مرورگر اینترنت اکسپلورر باز میشود را بوسیله مرورگر کروم باز کرد و از آن استفاده نمود.
لطفا سریع راهنمایی کنید وپاسخ را به ایمیلم ارسال کنید.
با تشکر

**Comment by molant** [comment]
@farzanefarahan this is not the place to ask for support. I recommend you to send a tweet to [@MSEdgeDev](https://twitter.com/MSEdgeDev)
