### ISSUE TITLE
Offline scan is trying to access online resources

### ISSUE THREAD

**Issue by homebrandcola** [MicrosoftEdge/static-code-scan#26]
I've been trying to setup an offline code scanner to can internal web resources. However whenever I try to scan an internal URL the application crashes with the following dump in the console:

C:\Users\Public\browser\modern.IE-static-code-scan-master>node app.js
Server started on port 1337
To scan a private url go to http://localhost:1337/ and follow the instructions

C:\Users\Public\browser\modern.IE-static-code-scan-master\node_modules\promised-
io\promise.js:242
                                                throw error;
                                                      ^
Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)

Looking at Wireshark I can see my machine trying to access the following online resources:

api.kraken.io
iecvlist.microsoft.com

Which it cannot.

If I connect the machine to the Internet and scan a publicly accessibly URL the scanner works, but when I am connected to the corporate network (to access internal URLs, and where I have no Internet access) the scanner crashes.

I might be able to get access to the resources through the corporate proxy, but how would I configure the scanner to use a proxy with a username and password? 

Thanks, Tim.

**Comment by Uzzol772** [comment]
thanks

**Comment by molant** [comment]
This project is deprecated and no longer maintained. Please check [sonar](https://github.com/sonarwhal/sonar) if you need a similar tool but more flexible and modern.
