### ISSUE TITLE
CSS prefix check is overly prefix-happy

### ISSUE THREAD

**Issue by dmethvin** [MicrosoftEdge/static-code-scan#53]
When encountering a prefix like `transition` the scan recommends `-webkit-`, `-moz-`, and `-o-` be added even though only Webkit ever implemented the prefixed version according to http://caniuse.com/#search=transition .

The report should only recommend adding prefixes that are still needed by deployed browsers, the caniuse.com site is probably the best source of info for that.

**Comment by molant** [comment]
This should be fixed now. Took a look with @dstorey and remove a bunch. We might remove a few more if we decide to not check for Android 2.x
