### ISSUE TITLE
Modern.ie doesn't read space-separated values in <link> rel attribute

### ISSUE THREAD

**Issue by BMSKiwi** [MicrosoftEdge/static-code-scan#55]
The <link> rel attribute contains a space-separated list of values, as per http://www.w3.org/TR/html5/document-metadata.html#attr-link-rel

A typical link on my site is:

    <link rel="next prefetch" href="results.html">

Modern.ie say my site lacks 'Flip Ahead Browsing' - presumably it has multiple space-separated values.

**Comment by molant** [comment]
Fixed via 21d71c82c4fd790bad26c9a475a0779bc21e796e
