### ISSUE TITLE
Update for IE11

### ISSUE THREAD

**Issue by dg9ngf** [MicrosoftEdge/static-code-scan#59]
Your website scan on modern.ie is a bit outdated. It only covers IE 9 
and 10, not 11. Here's the recommendation I got:

> canvas {
>     -ms-touch-action: double-tap-zoom;
> }

And this is from the referenced MSDN page:

> Note  As of Internet Explorer 11, the Microsoft vendor prefixed
> version of this event (-ms-touch-action) is no longer supported and
> may be removed in a future release. Instead, use the non-prefixed
> name touch-action, which is better for standards compliance and
> future compatibility.

There may also be other instances where the recommendations are not up-to-date.

**Comment by molant** [comment]
This is fixed in http://dev.modern.ie/tools/staticscan/

Thanks
