### ISSUE TITLE
Details on vendor-prefixed CSS attributes

### ISSUE THREAD

**Issue by dg9ngf** [MicrosoftEdge/static-code-scan#60]
I got a list of all attributes I used, but not what the issue is. I know 
that some attributes need to be prefixed for some browsers in certain 
versions. I also know that newer versions of these browsers partly don't 
need the prefixes anymore and I consider removing them for simpler code. 
(Mozilla MDN is a great resource for such information.) But what's the 
problem here?

**Comment by molant** [comment]
The css prefixes test has been updated and a bunch have been removed in the development branch. We are still adding some prefixes for webkit because of the large amount of android phones running old versions
