### ISSUE TITLE
Support Mobile Sites

### ISSUE THREAD

**Issue by BenjamP** [MicrosoftEdge/static-code-scan#68]
While at Smashing Conference, I received a request from developers to support mobile versions of sites in the code scanner. Today, it seems to only support default content. But if a site is built responsively, we should be able to scan the content given to mobile devices as well.

**Comment by molant** [comment]
This project is deprecated and no longer maintained. Please check [sonar](https://github.com/sonarwhal/sonar) if you need a similar tool but more flexible and modern.
