### ISSUE TITLE
Scan for unicode characters

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/static-code-scan#77]
I think it would be great if modern.ie had a warning for this where it scrapes the text and displays any Unicode characters.
- Here is the spec text: [Text Spec regarding showing control characters ](http://dev.w3.org/csswg/css-text/#white-space-processing)
- Discussion thread: https://lists.w3.org/Archives/Public/www-style/2014Nov/0282.html
- Agreement in minutes: https://log.csswg.org/irc.w3.org/css/2015-02-08/#e520449

**Comment by gregwhitworth** [comment]
Any updates on this?

**Comment by molant** [comment]
Nope, pretty busy with some other projects with hard deadlines. I do accept PR though... :)

**Comment by Uzzol772** [comment]
i can't upgread
