### ISSUE TITLE
scanner doesn't get results for www.skyscanner.com

### ISSUE THREAD

**Issue by smich73** [MicrosoftEdge/static-code-scan#93]
I have just tried to site scanner but it doesn't work with my url.
I don't want to share the url publically but please reach out to me on this.

When I try it I see the message:

We encountered an error with this URL.

Try the following options:

•Enter your domain name only
•Use a destination URL if the original URL you entered redirects to it
•Download the offline version to analyze pages that are behind a firewall or require a user to authenticate to access

Thanks

**Comment by molant** [comment]
Are you having problems with the version in dev.modern.ie or this one?
Is there URL publicly accessible?
If it isn't or it is behind a password it will not work with the public scanner.

-----Original Message-----

**Comment by smich73** [comment]
Hi Anton
 
The URL is publically accessible with no password.
I didn't want to post it live for business reason.
 
Address is:
http://www.skyscanner.net/
 
Doesn't seem to work at all - not in the link below either
 
thanks
Simon
 
Date: Thu, 6 Aug 2015 06:02:44 -0700

**Comment by molant** [comment]
OK, thanks. I'll take a look as soon as I have some available time.

**Comment by smich73** [comment]
Thank you Anton.
I work for MS UK and this is one of my partners.
Do you have an eta on when we will know more info on this as i have a potential meeting with the client ina few weeks time

Thanks

**Comment by molant** [comment]
You can download the scanner and run it locally to get more info about why it crashes. That should be faster than waiting for me to have some free time to look at it.

**Comment by smich73** [comment]
Ok thanks, will try that and let you know any feedback

**Comment by molant** [comment]
@smich73 stop looking. The issue is not in the scanner but in the website. Change should be deployed in the next few days. The local copy works without any issue

**Comment by smich73** [comment]
Perfect - thanks very much

Sent from my Windows Phone
________________________________
