### ISSUE TITLE
images with alt="" are flagged as error

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/static-code-scan#94]
Steps:

http://dev.modern.ie/tools/staticscan/?url=http%3A%2F%2Fs.codepen.io%2Fboomerang%2F3ed1813955cbc0f3777b36397e66cc281438899331621%2Findex.html

Expected:

No errors for missing alt attribute as there is a valid alt="". 

Actual:

Shows an error that the alt attribute is missing.

**Comment by timothya** [comment]
https://github.com/MicrosoftEdge/static-code-scan/blob/master/lib/checks/check-accessibility-alt.js#L24

The code explicitly looks for images with empty alt attributes.
