### ISSUE TITLE
Test are outdated and don't pass

### ISSUE THREAD

**Issue by KevinBurton** [MicrosoftEdge/static-code-scan#95]
In addition to the installation instauctions I did
npm install grunt-controb-watch
npm install -g grunt-cli
Then I ran 'grunt nodeunit' in the static-code-scan folder from the zip download. I received the following error message(s):

Running "nodeunit:all" (nodeunit) task
Testing altImg_test.js.F..
>> AltImg - Empty alt attribute
>> Message: http://localhost:1338/altImg-2.html passed: true !== false
>> Error: true == false
>> at C:\Users\KBurton\Downloads\static-code-scan-master\test\altImg_test.js:47
22
>> at tryCatcher (node_modules\bluebird\js\main\util.js:26:23)
>> at Promise._settlePromiseFromHandler (node_modules\bluebird\js\main\promise.
s:503:31)
>> at Promise._settlePromiseAt (node_modules\bluebird\js\main\promise.js:577:18

>> at Promise._settlePromiseAtPostResolution (node_modules\bluebird\js\main\pro
ise.js:244:10)
>> at Async._drainQueue (node_modules\bluebird\js\main\async.js:128:12)
>> at Async._drainQueues (node_modules\bluebird\js\main\async.js:133:10)
>> at Immediate.Async.drainQueues [as _onImmediate] (node_modules\bluebird\js\m
in\async.js:15:14)
>> at processImmediate [as _immediateCallback] (timers.js:367:17)

Testing aria_test.js.....OK
Testing browserdetection_test.js........OK
Server started on port 1337
To scan a private url go to http://localhost:1337/ and follow the instructions
Fatal error: undefined is not a function

Ideas?

**Comment by molant** [comment]
tests are completely out of date so this is (unfortunately) expected.
If you run node app.js it should work as expected

**Comment by molant** [comment]
Fixed via 45bba60dca3d41c1daa3baacbc4c2e196e7d1b0a
