### ISSUE TITLE
Auth based unit test don't actually test auth code

### ISSUE THREAD

**Issue by m-gagne** [MicrosoftEdge/static-code-scan#99]
# Description
The auth based unit tests don't actually apply code coverage to the express web app but rather uses a custom (test only) auth server (based on express). These tests not only currently do not work, but do not add value to the unit tests.

# Recommendation
Remove the tests

**Comment by molant** [comment]
I think we should still have the auth tests (and probably improve them) for when NTLM support is added. That is going to change significantly how resources are downloaded and a few things could go wrong...

**Comment by m-gagne** [comment]
From what I can see in the code, they would need a rewrite, as they are not testing any actual production code, simply mimicking a basic auth server. We can revert the PR for this and comment out the code, but it didn't really do anything anyways.
